const data = [
  {
    brand: 'Aprilia',
    models: [
      {
        model: 'RS 50',
        lastSupportedYear: 1994,
        chainChangePrice: 85,
        oilAndOilFilterChangePrice: 23,
        airFilterChangePrice: 18,
        brakeFluidChangePrice: 44,
      },
      {
        model: 'Tuono',
        lastSupportedYear: 1995,
        chainChangePrice: 77,
        oilAndOilFilterChangePrice: 20,
        airFilterChangePrice: 24,
        brakeFluidChangePrice: 42,
      },
      {
        model: 'RSV4 1100',
        lastSupportedYear: 1991,
        chainChangePrice: 80,
        oilAndOilFilterChangePrice: 42,
        airFilterChangePrice: 17,
        brakeFluidChangePrice: 23,
      },
      {
        model: 'RSV4 125',
        lastSupportedYear: 1996,
        chainChangePrice: 58,
        oilAndOilFilterChangePrice: 32,
        airFilterChangePrice: 22,
        brakeFluidChangePrice: 38,
      },
      {
        model: 'RS 125',
        lastSupportedYear: 1992,
        chainChangePrice: 56,
        oilAndOilFilterChangePrice: 22,
        airFilterChangePrice: 30,
        brakeFluidChangePrice: 32,
      },
      {
        model: 'SR 50',
        lastSupportedYear: 1995,
        chainChangePrice: 83,
        oilAndOilFilterChangePrice: 28,
        airFilterChangePrice: 20,
        brakeFluidChangePrice: 39,
      },
      {
        model: 'SR 125',
        lastSupportedYear: 1994,
        chainChangePrice: 82,
        oilAndOilFilterChangePrice: 23,
        airFilterChangePrice: 25,
        brakeFluidChangePrice: 28,
      },
    ],
  },
  {
    brand: 'Ducati',
    models: [
      {
        model: 'Panigale V4',
        lastSupportedYear: 1996,
        chainChangePrice: 71,
        oilAndOilFilterChangePrice: 30,
        airFilterChangePrice: 26,
        brakeFluidChangePrice: 45,
      },
      {
        model: 'Scrambler 800',
        lastSupportedYear: 1991,
        chainChangePrice: 93,
        oilAndOilFilterChangePrice: 44,
        airFilterChangePrice: 23,
        brakeFluidChangePrice: 41,
      },
      {
        model: 'Diavel',
        lastSupportedYear: 1991,
        chainChangePrice: 70,
        oilAndOilFilterChangePrice: 22,
        airFilterChangePrice: 29,
        brakeFluidChangePrice: 35,
      },
      {
        model: 'Monster',
        lastSupportedYear: 1991,
        chainChangePrice: 86,
        oilAndOilFilterChangePrice: 26,
        airFilterChangePrice: 17,
        brakeFluidChangePrice: 25,
      },
      {
        model: 'Panigale V2',
        lastSupportedYear: 1991,
        chainChangePrice: 91,
        oilAndOilFilterChangePrice: 32,
        airFilterChangePrice: 15,
        brakeFluidChangePrice: 23,
      },
      {
        model: 'Hypermotard',
        lastSupportedYear: 1991,
        chainChangePrice: 68,
        oilAndOilFilterChangePrice: 39,
        airFilterChangePrice: 20,
        brakeFluidChangePrice: 39,
      },
      {
        model: 'Streetfighter',
        lastSupportedYear: 1996,
        chainChangePrice: 91,
        oilAndOilFilterChangePrice: 23,
        airFilterChangePrice: 28,
        brakeFluidChangePrice: 38,
      },
    ],
  },
  {
    brand: 'Yamaha',
    models: [
      {
        model: 'MT-03',
        lastSupportedYear: 1995,
        chainChangePrice: 75,
        oilAndOilFilterChangePrice: 36,
        airFilterChangePrice: 29,
        brakeFluidChangePrice: 34,
      },
      {
        model: 'MT-07',
        lastSupportedYear: 1991,
        chainChangePrice: 50,
        oilAndOilFilterChangePrice: 43,
        airFilterChangePrice: 27,
        brakeFluidChangePrice: 43,
      },
      {
        model: 'MT-09',
        lastSupportedYear: 1994,
        chainChangePrice: 92,
        oilAndOilFilterChangePrice: 26,
        airFilterChangePrice: 20,
        brakeFluidChangePrice: 40,
      },
      {
        model: 'R1',
        lastSupportedYear: 1993,
        chainChangePrice: 48,
        oilAndOilFilterChangePrice: 38,
        airFilterChangePrice: 25,
        brakeFluidChangePrice: 40,
      },
      {
        model: 'R6',
        lastSupportedYear: 1995,
        chainChangePrice: 74,
        oilAndOilFilterChangePrice: 29,
        airFilterChangePrice: 27,
        brakeFluidChangePrice: 38,
      },
      {
        model: 'R7',
        lastSupportedYear: 1991,
        chainChangePrice: 87,
        oilAndOilFilterChangePrice: 45,
        airFilterChangePrice: 28,
        brakeFluidChangePrice: 22,
      },
      {
        model: 'R125',
        lastSupportedYear: 1991,
        chainChangePrice: 52,
        oilAndOilFilterChangePrice: 44,
        airFilterChangePrice: 24,
        brakeFluidChangePrice: 28,
      },
    ],
  },
  {
    brand: 'Kawasaki',
    models: [
      {
        model: 'Ninja H2',
        lastSupportedYear: 1995,
        chainChangePrice: 48,
        oilAndOilFilterChangePrice: 37,
        airFilterChangePrice: 28,
        brakeFluidChangePrice: 26,
      },
      {
        model: 'Ninja 300',
        lastSupportedYear: 1992,
        chainChangePrice: 44,
        oilAndOilFilterChangePrice: 38,
        airFilterChangePrice: 23,
        brakeFluidChangePrice: 26,
      },
      {
        model: 'Ninja 650',
        lastSupportedYear: 1991,
        chainChangePrice: 69,
        oilAndOilFilterChangePrice: 33,
        airFilterChangePrice: 27,
        brakeFluidChangePrice: 29,
      },
      {
        model: 'Ninja ZX-10R',
        lastSupportedYear: 1993,
        chainChangePrice: 50,
        oilAndOilFilterChangePrice: 34,
        airFilterChangePrice: 24,
        brakeFluidChangePrice: 38,
      },
      {
        model: 'Z750',
        lastSupportedYear: 1993,
        chainChangePrice: 82,
        oilAndOilFilterChangePrice: 30,
        airFilterChangePrice: 19,
        brakeFluidChangePrice: 27,
      },
      {
        model: 'Z900',
        lastSupportedYear: 1995,
        chainChangePrice: 89,
        oilAndOilFilterChangePrice: 37,
        airFilterChangePrice: 26,
        brakeFluidChangePrice: 43,
      },
    ],
  },
  {
    brand: 'Suzuki',
    models: [
      {
        model: 'Hayabusa',
        lastSupportedYear: 1994,
        chainChangePrice: 44,
        oilAndOilFilterChangePrice: 36,
        airFilterChangePrice: 24,
        brakeFluidChangePrice: 28,
      },
      {
        model: 'Burgman 400',
        lastSupportedYear: 1992,
        chainChangePrice: 58,
        oilAndOilFilterChangePrice: 41,
        airFilterChangePrice: 15,
        brakeFluidChangePrice: 30,
      },
      {
        model: 'GSX 600R',
        lastSupportedYear: 1992,
        chainChangePrice: 95,
        oilAndOilFilterChangePrice: 42,
        airFilterChangePrice: 30,
        brakeFluidChangePrice: 43,
      },
      {
        model: 'GSX 1000R',
        lastSupportedYear: 1994,
        chainChangePrice: 80,
        oilAndOilFilterChangePrice: 43,
        airFilterChangePrice: 24,
        brakeFluidChangePrice: 24,
      },
      {
        model: 'GSX 750R',
        lastSupportedYear: 1996,
        chainChangePrice: 79,
        oilAndOilFilterChangePrice: 36,
        airFilterChangePrice: 22,
        brakeFluidChangePrice: 25,
      },
      {
        model: 'GSX 750S',
        lastSupportedYear: 1995,
        chainChangePrice: 49,
        oilAndOilFilterChangePrice: 45,
        airFilterChangePrice: 15,
        brakeFluidChangePrice: 22,
      },
      {
        model: 'GSX 1000S',
        lastSupportedYear: 1995,
        chainChangePrice: 100,
        oilAndOilFilterChangePrice: 41,
        airFilterChangePrice: 17,
        brakeFluidChangePrice: 30,
      },
      {
        model: 'GSR 600',
        lastSupportedYear: 1995,
        chainChangePrice: 99,
        oilAndOilFilterChangePrice: 42,
        airFilterChangePrice: 17,
        brakeFluidChangePrice: 43,
      },
      {
        model: 'GSR 750',
        lastSupportedYear: 1993,
        chainChangePrice: 57,
        oilAndOilFilterChangePrice: 30,
        airFilterChangePrice: 19,
        brakeFluidChangePrice: 36,
      },
      {
        model: 'GSR 1000',
        lastSupportedYear: 1993,
        chainChangePrice: 72,
        oilAndOilFilterChangePrice: 41,
        airFilterChangePrice: 29,
        brakeFluidChangePrice: 31,
      },
    ],
  },
];

export default data;
